### PR TITLE
Add `multi` value support for Listbox & Combobox

### PR DESCRIPTION
**Pull request by RobinMalfait**
This PR will add `multiple` values support for both the `Listbox` and `Combobox` components.

You can enable multiple value support by providing an array of items instead of a single value. When the `value` is an array, we automatically switch to multiple value mode.

This has a few implications:
- Underlying aria attributes will be a bit different, but you don't have to worry about this.
- When you are in multiple value mode, then the Listbox/Combobox will stay open when activating items.
  - This is to prevent that you have to re-open every time you make a change.
- When you are in multiple value mode, then activating an option will function as a "toggle". So that it is possible to "unselect" a value.
- The value passed to the `v-model` in Vue, and the `onChange` in React will now be an array.

You can play with it here: 
- Listbox
  - React: https://headlessui-react-git-multi-value-support-tailwindlabs.vercel.app/listbox/multi-select
  - Vue: https://headlessui-vue-git-multi-value-support-tailwindlabs.vercel.app/listbox/multi-select
- Combobox
  - React: https://headlessui-react-git-multi-value-support-tailwindlabs.vercel.app/combobox/multi-select
  - Vue: https://headlessui-vue-git-multi-value-support-tailwindlabs.vercel.app/combobox/multi-select

Closes: #648

### CODE REVIEW

**Comment by getreworked** [comment]
This is fantastic news - looking forward to having this merged in. Thank you for all your hard work with Headless UI 🙏

**Comment by brandonleichty** [comment]
This PR couldn't have come at a more perfect time!

**Comment by greendesertsnow** [comment]
Oh I'm signing out of happiness!

**Comment by greendesertsnow** [comment]
Oh I'm singing out of happiness!

**Comment by parssak** [comment]
When can we expect to see this in an official release?

**Comment by preeteshjain** [comment]
So happy to see this. Thank you so much for the hardwork guys, this was much much needed! ❤️

**Comment by nynevi** [comment]
for people wondering what happened, it is in the insiders release:
https://github.com/tailwindlabs/headlessui/pull/648#issuecomment-1074211598

**Comment by feruz111** [comment]
Hey just wondering, if the multi select Listbox is in yet as for now (React)

**Comment by RobinMalfait** [comment]
@feruz111 Yep! Was released in April of 2022 (version [1.6.0](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v1.6.0))

**Pull request merged**
