### PR TITLE
Fix `displayValue` syncing problem

### LINKED ISSUE #1735: [Bug][Severe] Using `Combobox.Input` with `displayValue` breaks the input behaviour
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

Bug found in : `0.0.0-insiders.fa10cb0`
Works fine with `1.6.6`

**What browser are you using?**

N/A

**Reproduction URL**

https://stackblitz.com/edit/react-onn88a?file=src/App.js

**Describe your issue**

Focus the input and start editing its value. You will see after a few ms it will return to the value returned by `displayValue`. 
Up to `1.6.6` the behaviour was to keep the user input while he's editing.

May be related to issue #1675, PR #1679.

### PR DESCRIPTION
**Pull request by thecrypticace**
Fixes #1735

### CODE REVIEW

**Comment by JesusTheHun** [comment]
Hi,

This PR breaks the fix provided to #1675 .
The test named `conditionally rendering the input should allow changing the display value` has been overwritten by another test while keeping its name, and does not test said behaviour.

**Comment by JesusTheHun** [comment]
@thecrypticace @RobinMalfait did you have a chance to take a look at my previous message ? This blocks a big release on my software, quite annoying :/ If I can be of any help, let me know.

**Comment by thecrypticace** [comment]
Hey @JesusTheHun sorry we didn't see your old message. Comments on older issues tend to get lost. I've added this to our internal todo list to take a look. Thanks for bringing it up.

**Comment by JesusTheHun** [comment]
Hello @thecrypticace, do you have any ETA on this ?
Also, would you mind re-opening this issue ? It makes me feel nervous that it might be forgotten again 😅
Some love from France <3

**Comment by thecrypticace** [comment]
Sorry, not at the moment. We have been crazy busy with Tailwind CSS v3.2! And have some other things coming up soon. I've reopened the issue and will take a look as soon as I can.

**Pull request merged**
